### ISSUE TITLE
Review Checkins initial upload and plan modifications

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#13]
- [x] Verify Worship channel is correct
- [x] Review EventTime.Name instead of using Service time to avoid timezone calculations => is this okay?
- [x] Verify Activity title is correct
- [x] Added link to the Api data for the checkin => Is this useful? Should it link to the planning center app?
- [x] Activity type => "Online Worship Attendance"
- [ ] Description Field => Used placeholder text, but can use other text
- [x] Weight = 5 works
- [x] adding a tag of "channel:Worship" appears to work
- [x] Do any members have different attendance than in the main workspace?

Note: The love column takes some time to populate properly (at least a couple hours)

**Comment by revsean** [comment]
### **Questions**
- **RE: Activity Type:** The activity type of online worship attendance currently works. How are you thinking of differentiating when we also have in-person? Could we add "In-Person" or "Online" to the EventTime.name and do a conditional if we a "contains" function? 

- **Do any members have different attendance than in the main workspace?**  Attendance looks the same between the two systems, at least for this last Sunday. 

### **Comments**
-  Using EventTime.Name: This works well. I can go and rename them in PCO to have them make more sense. 

-  API Data Link:  --> replace link w/ https://check-ins.planningcenteronline.com/people/ACXXXXXXXXX/activity where XXXXXXX is their pco id. 

-   Description Field-> I don't think we need this field. 

### **No Issues:**
- Verify Worship channel is correct
-  Verify Activity title is correct
-  Activity type => "Online Worship Attendance"
-  Weight = 5 works
-  adding a tag of "channel:Worship" appears to work
- Activity type => "Online Worship Attendance"

**Comment by samhowes** [comment]
1. RE: Activity Type: Punting conversation to issue #7 
2. It looks like https://check-ins.planningcenteronline.com/people/ACXXXXXXXXX/activity links to ALL the activity for a particular person. This seems like a potentially useful link, however, I'm going to try uploading a link to the checkin itself, for example: https://check-ins.planningcenteronline.com/event_periods/15905618/check_ins/220553844 
    Follow up in issue #15
