### ISSUE TITLE
Importing Historical Worship Attendance from another Check-In 

### ISSUE THREAD

**Issue by revsean** [samhowes/foothills-data#14]
Apparently, we have another Check-in event called Sunday Worship that has old historical worship data.  Once we have the rest set up we can run an export of this one.

**Comment by samhowes** [comment]
There are a lot of other events that are registered in there. 

Sounds like you'd want `Sunday Worship` to be the same Activity as `Sunday Attendance`, but we could also attempt to classify those other events as other activities?

Some examples below. They all have the same fields, they also have other data attached that we can use to categorize. 

1. https://api.planningcenteronline.com/check-ins/v2/events/426427
    ```
    Name: Weekly Heart Check-In
    Frequency: Weekly
    EnableServicesIntegration: False
    CreatedAt 2021-05-07T14:16:04Z
    IntegrationKey: null
    LocationTimesEnabled: True
    PreSelectEnabled: False
    ```
1. 
    ```
    Name: Church Governance Events
    Frequency: None
    ```
1. 
    ```
    Name: Fireside Chat with the Board
    Frequency: Daily
    ```

**Comment by samhowes** [comment]
First thought: we could categorize each event by weekly, daily, or None and put those as separate activities

**Comment by revsean** [comment]
Two Parts:

1. Bringing Sunday Worship in like Sunday attendance makes sense to me. Although it looks like most of that data would be In-Person Attendance. 
2. For the other mountain of check-in data, I need to think about the best way to categorize it.

**Comment by revsean** [comment]
We're running into the same issue we have with groups when we think about bringing data over. They need to be sorted into a few channels. Is there any fields we could use to auto sort those?

**Comment by revsean** [comment]
Think we can merge this with another issue, no?

**Comment by samhowes** [comment]
I believe this has been accounted for.
