### ISSUE TITLE
Update Activity Link for CheckIns to link to app instead of api

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#15]
Options:
1. Link to the member's profile in "checkins" This could be useful to simply review a member's activity 
    `https://check-ins.planningcenteronline.com/people/AC97560346/activity`
     ![image](https://user-images.githubusercontent.com/6216665/133348563-517b0fa1-eba6-47c7-91be-472e9c83ad67.png)

2. Link to the exact checkin. This could be more useful for reviewing specific historical checkins: 
    `https://check-ins.planningcenteronline.com/event_periods/15905618/check_ins/220553844`
    ![image](https://user-images.githubusercontent.com/6216665/133348469-b1562c6e-aba4-4263-a8b1-fe0a5b6baf4e.png)

**Comment by samhowes** [comment]
Either way, I think linking to a User's activity log (Option 1) is useful, we may want to put that link in the member's profile though. Happy to do either.

**Comment by revsean** [comment]
Yeah... I have to think. having it go to the specific check-in allows us to easily see more context about that instance (but it might be a useful practice to use for all future links just to keep them consistence).

**Comment by samhowes** [comment]
Check out the updated links for https://app.orbit.love/sam-workspace/members/59719089?activity_type=custom 

I cleared the description of the CheckIn, and updated the link to point to the specific checkin

Thoughts?

![image](https://user-images.githubusercontent.com/6216665/133361485-8961e62a-4bba-405e-8f56-5321f1ec7461.png)

**Comment by samhowes** [comment]
@revsean

**Comment by samhowes** [comment]
@revsean approves, closing.
