### ISSUE TITLE
Donations to specific funds

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#16]
- [x] Initial upload
- [x] Review data
- [x] Exclude Refunds
- [x] Update donation link
- [x] Find donations that don't have a person for Sean to inspect

**Comment by samhowes** [comment]
@revsean I see a `refunded` field, do we want to exclude refunds?

**Comment by samhowes** [comment]
25598 out of 25178 donations uploaded as activities, 1965 skipped due to either an excluded fundId or missing a person attached.

@revsean take a look and let me know what you think.

**Comment by revsean** [comment]
1. Yes to excluding refunds, 
2. Donation link https://giving.planningcenteronline.com/donations/101750538 . Assume the number is the donation ID
3. My back of the napkin math says that it captured pretty much all the donation data. Stellar!

**Comment by samhowes** [comment]
@revsean these updates should be in now. A heads up though, as part of this update, I temporarily deleted some checkin data. I will be re-uploading that checkin data once my upload of Donations completes, it's currently on 2019-03-10

**Comment by samhowes** [comment]
Donations missing a person punted to #17

**Comment by samhowes** [comment]
Donations upload complete, app link is updated.
![image](https://user-images.githubusercontent.com/6216665/133891154-8090383c-2a1a-4848-a25f-6fea21fd817c.png)

@revsean please review and close if it looks good.

**Comment by revsean** [comment]
Works perfect.
