### ISSUE TITLE
Decide what to do when objects in Planning Center don't have a person attached

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#17]
Sometimes Planning Center does not return a person for a particular object
I can come up with examples for each if necessary
- [x] CheckIns: Maybe this is a guest checkin? I'm currently ignoring these
- [x] Donations: I assume this is an anonymous donation, we could create an "anonymous" member and log donations against that

**Comment by revsean** [comment]
1. Guest check-ins: yes that wouldn't create a profile. I try to get the team not to use these ever but they get confused. 
2. I don't think it's possible for our system to take anonymous donations... we have some donations attributed to a profile called anonymous. Can you point me to details on a donation that doesn't have a person so I can try to track it down.

**Comment by samhowes** [comment]
1. So we'll continue ignoring this data even though there might be some valid, yet accidental checkins? 
1. Yep, I'll grab a couple and update.

**Comment by revsean** [comment]
1. Yes-- If they don't have a profile then we can't allocate the data to anywhere meaningful.

**Comment by samhowes** [comment]
Finally got to it, here are some donations that don't have people attached:
 https://giving.planningcenteronline.com/donations/99840405
Looks like this one was part of a "batch"?
![image](https://user-images.githubusercontent.com/6216665/133887724-ea07c584-efc4-47fe-858b-7e08c81ee0e9.png)


https://giving.planningcenteronline.com/donations/86429688, Batch: 546
https://giving.planningcenteronline.com/donations/77851922, Batch: 525
https://giving.planningcenteronline.com/donations/88762460, Batch: 549

There are more, but they all seem to have a batch id associated

**Comment by revsean** [comment]
Yes we can ignore these.
