### ISSUE TITLE
Sync all CheckIns that have `(Channel:<channelname>)` in the title

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#20]

**Comment by samhowes** [comment]
Using the following regex for this: `(\(|\[)(ch)(annel)?:.*(\)|\])` with case INsensitive settings

This can be tested here: https://regexr.com/65tj4

![image](https://user-images.githubusercontent.com/6216665/133941336-8f3784b2-6cca-423d-9be6-21311c04d79d.png)

**Comment by samhowes** [comment]
Upload in progress, ready for review


![image](https://user-images.githubusercontent.com/6216665/133942486-1cadfdee-b38b-4868-985a-cff4a35dd45a.png)

![image](https://user-images.githubusercontent.com/6216665/133942509-68e85167-8456-4cfd-97f3-45d743a97ce5.png)

**Comment by revsean** [comment]
I have gone through and added all channel designations to check-ins. I did realize I needed a new channel called Governance.

**Comment by revsean** [comment]
Question: How are we defining Activity Types for non-worship events?

**Comment by samhowes** [comment]
Looks like I'm just using Event.Name as the activity type

**Comment by revsean** [comment]
That might be a problem as adding a custom name for the events is a new feature we haven't used beyond worship. Maybe this is where some of the errors came from. Can we give it a field to use if Event.Name is not defined?

**Comment by samhowes** [comment]
@revsean on the phone we discussed:
1. Using EventTime.Name for Worship channel Activity Types
2. Using a specific name for all other Checkins for Activity Type

What exact text would you like for the non-worship ActivityType?

**Comment by revsean** [comment]
Event Check-in
