### ISSUE TITLE
Group Membership 

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#24]
- [x] Initial Upload of members joining groups that have channels as group attendance
- [x] (@revsean) review data
- [ ] Address feedback

**Comment by samhowes** [comment]
Upload in progress, first results:
![image](https://user-images.githubusercontent.com/6216665/133932701-b8bcf8ae-3f06-498d-a53c-73c0647d1fb6.png)

**Comment by revsean** [comment]
Looks great to me.
