### ISSUE TITLE
Activity Type in Spiritual Deepening 

### ISSUE THREAD

**Issue by revsean** [samhowes/foothills-data#27]
![Screen Shot 2021-09-22 at 9 33 37 AM](https://user-images.githubusercontent.com/86415336/134374801-3250d637-f4d2-4f0c-afcd-5b7b2eff24bd.png)

Was looking at the Spiritual Deepening Channel and noticed a few activity types that were odd. 

Activity types:

- BaseCamp - The Starting Place for Newcomers (Channel:SpiritualDeepening)

- BaseCamp - The Starting Place for Newcomers ([link](https://app.orbit.love/sam-workspace/activities?activity_type=custom%3ABaseCamp+-+The+Starting+Place+for+Newcomers&affiliation=member&channel=SpiritualDeepening))

Could just be how they were pulled in as I have just added all the (Ch:XXXXXX) designations.

**Comment by samhowes** [comment]
I think this is an accidental upload of a couple activities before I filtered out the suffix.

I'm planning on starting a fresh upload to a new workspace, this should not be present in the new upload, Let's leave this open until we confirm though.

**Comment by revsean** [comment]
That's what I assumed.


*Rev. Sean Neil-Barron*
he /him / his
Associate Minister
Foothills Unitarian Church
m: 617.817.0531
e: ***@***.***

**Comment by samhowes** [comment]
closing in favor of #19
