### ISSUE TITLE
Activities uploaded with Type = `Custom` 

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#29]
Discovered with initial upload in #19

**Comment by revsean** [comment]
Seems the caring notes lost their custom activity type. https://app.orbit.love/sam-test/activities?affiliation=member&channel=Caring

**Comment by samhowes** [comment]
This appears to be resolved except for one single activity. I'll investigate that one in particular.

**Comment by revsean** [comment]
Looks resolved on my end.
