### ISSUE TITLE
Apply the child tag to people of a particular membership type

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#3]
- [x] Dynamically choose which workspace to upload data to if the person is a child or not

**Comment by revsean** [comment]
In the future, I'd love to have children in their own separate workspace. So maybe it's easiest to just filter them out entirely right now. 

Two fields that contain that data are:

- Membership Type=  Participant (Child)
- Child = True

**Comment by samhowes** [comment]
If you create that workspace now, its pretty trivial for me to just make the workspace that I upload to conditional on the child. It is a very simple parameter when I'm processing things.

**Comment by revsean** [comment]
I already set up a workspace and I think it should work with the same API token https://app.orbit.love/familyministry

So if it is easy to just sort them in now, that would be grand.
