### ISSUE TITLE
Link to a Planning Center profile instead of the api link

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#5]

**Comment by revsean** [comment]
Here are all the Apps and their PCO Profile links. The numbers after AC are their pco profile id

https://giving.planningcenteronline.com/people/AC83314870
 https://check-ins.planningcenteronline.com/people/AC83314870
https://groups.planningcenteronline.com/people/AC83314870
https://people.planningcenteronline.com/people/AC83314870
https://registrations.planningcenteronline.com/people/AC83314870
https://services.planningcenteronline.com/people/AC27642562/

**Comment by samhowes** [comment]
already done in other work
