### ISSUE TITLE
Distinguish between InPerson Checkins and Online Checkins

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#7]
- [x] Update to use location data
- [x] Update to use configured dates

**Comment by revsean** [comment]
Could we put a piece of text into EventTime.Name that we query to differentiate? 

If EventTime.Name contains "Online" then Activity type = Online Worship Attendance 

If EventTime.Name contains "InPerson" then Activity type = InPerson Worship Attendance

**Comment by samhowes** [comment]
What about utilizing the Locations feature of Checkins? You could configure an "In Person" Location and an "Online" Location and select that location when a checkin happens. Not sure how conducive that is for the workflow that is followed for whomever actually checks someone in.

With a closer look at the UI, it appears that it allows you to restrict the locations of a particular EventTime:

![image](https://user-images.githubusercontent.com/6216665/133347791-535bd146-4bef-4322-b029-a6fa04b203eb.png)

![image](https://user-images.githubusercontent.com/6216665/133347867-6a639a48-b7b1-4ebb-a080-69235f8e88f1.png)

![image](https://user-images.githubusercontent.com/6216665/133347369-233346f6-90fa-4b1c-be87-b7dc9afa4150.png)

![image](https://user-images.githubusercontent.com/6216665/133347950-69baf8af-d41b-472b-a36f-50fd7fe03434.png)

**Comment by revsean** [comment]
That seems like a perfect solution.

**Comment by revsean** [comment]
I won't be able to change the location data retroactively but I can set that up going forward,

**Comment by samhowes** [comment]
Sounds good! Update and assign back to me once you have a Location configured for an Event so I can see how it looks from the Api's perspective.

**Comment by revsean** [comment]
Configured the Sunday Attendance event to have those locations. I then went and retroactively shifted some of the Sept 13th check-ins to have an Online location.

**Comment by samhowes** [comment]
How do we want to handle past checkins? I can hardcore a particular date or something to upload them all as "online attendance", and then use location going forward?

**Comment by samhowes** [comment]
Also, thanks, I'll check that out from the api now.

**Comment by revsean** [comment]
For Sunday Attendance Check In Event:

- Before March 15th 2020 - In-Person
- Between March 15th 2020-September 12 2021  Online
- After Sept 12 - Use locations.

**Comment by samhowes** [comment]
@revsean I'm seeing an extra location named "Welcome Table" :

`opened` is false, so it's possible that no one can check into it?

If Welcome Table is an "In Person" type of location, it's possible you can create a "Folder" of locations to designate multiple locations as "in person":
(from the api docs)
![image](https://user-images.githubusercontent.com/6216665/133905334-ad9bdf1c-a0e3-4c06-8d42-daf2a8702258.png)


![image](https://user-images.githubusercontent.com/6216665/133905272-44ed12a4-c607-468c-bb96-8ad7b6ba32b4.png)

**Comment by samhowes** [comment]
From the call:
@revsean will rename "Welcome Table" to "Online". "opened:false" prevents people from being checked in at that location.

Location.Name will directly be used as the ActivityType. Since it is in the channel "Worship", we are not concerned about any other qualifiers on the ActivtyType.

**Comment by samhowes** [comment]
Current checkin data has `(Channel:Worship)` included in the activity title, this will be removed via #20
