### ISSUE TITLE
Group Attendance (Member & Leader) => Activity

### ISSUE THREAD

**Issue by samhowes** [samhowes/foothills-data#9]
- [x] @revsean to tag all groups so the code can upload to the appropriate channel
- [x] Initial Upload
- [x] (@revsean) review data
- [x] Address feedback

**Comment by revsean** [comment]
I have all but 4 groups tagged correctly, need to chat with my colleagues about the last four.

**Comment by revsean** [comment]
Edged cases eliminated. I also went and added tags to most archived groups.  The ones that have no channel tag should be added to Belonging & Community.

**Comment by samhowes** [comment]
@revsean Mostly an FYI: It appears Orbit api transforms a channel that has spaces and some special characters in it:

So far "Belonging & Community" got turned into "Belonging-community"

Because of some of the update management I have to do, I'll have to write some custom code to get my code to compute the same value as the api. 

![image](https://user-images.githubusercontent.com/6216665/133897403-f1167fd2-376c-4d89-a641-9f5b10531200.png)

The following can be done:

1. Nothing, this is fine
2. @revsean updates the group channel names to not include spaces or special characters so things appear the same in Planning Center as they do in Orbit
3. So we don't have to rely on the api's custom transformation logic changing, @samhowes can use the code that he's writing anyways to eagerly transform group names in the upload client for maximum safety

@revsean thoughts?

API call:

![image](https://user-images.githubusercontent.com/6216665/133897513-3f66f0cc-5924-49b9-a4a9-e22fcf5e5ecf.png)

**Comment by samhowes** [comment]
@revsean In case you wanted an inventory of casing strategies:

1. kebab-case
2. PascalCase
3. camelCase
4. snake_case

It looks like it is simply replacing spaces with dashes and removing special characters. Which means it is mixing PascalCase and kebab-case. My first instinct would be to choose a casing strategy and stick with that. For this instance, I would choose PascalCase, i.e. `BeloningCommunity`, unless you choose to update the group tag to `BelongingAndCommunity` or something else.

**Comment by samhowes** [comment]
We decided to enforce PascalCase.

**Comment by samhowes** [comment]
@revsean ready for review

**Comment by revsean** [comment]
Looks good to me.

**Comment by revsean** [comment]
Just realized something: We should probably create a new Activity type for the 'joined' a group to differentiate between attendance and group membership. Group Membership = Joined. Group Attendance = Event Attendance
